### ISSUE TITLE
can you please open the disscussion forum please

### ISSUE THREAD

**Issue by fms12** [ibcoder001/gyan-fortress#10]

**Comment by ibcoder001** [comment]
As in? Can you please elaborate more?

**Comment by fms12** [comment]
![image](https://user-images.githubusercontent.com/68012074/212449925-28b2b2d1-f5a2-4ff7-9034-fca455fcecaa.png)
like this so we can discuss easily what we are doing and if have a problem/issue regarding the project so  we can discuss there

**Comment by fms12** [comment]
![image](https://user-images.githubusercontent.com/68012074/212450027-9b22dc60-ad46-447b-ad10-a8524001a274.png)
or can you add a project inside projects so we can keep track of the task like the above.

**Comment by ibcoder001** [comment]
Created a feature project template for the same. Will make it public once I figure it out and organize it. Also created the discussion for the project.

Thanks @fms12 for help.

**Comment by ibcoder001** [comment]
I'm closing this issue as it's resolved.
